services:
  - type: web
    name: photo-spot
    env: python
    startCommand: gunicorn photoshoot.wsgi:application
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
